/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author HoangVanToan
 */
// import thư viện và các form cần sử dụng
import view.V_DangNhap;
import view.V_ThayDoiMatKhau;
import view.V_ThemDiem;
import view.V_ThemLop;
import view.V_ThemMonHoc;
import view.V_ThemSinhVien;
import view.V_ThemTaiKhoan;
import view.V_XoaDiem;
import view.V_XoaLop;
import view.V_XoaMonHoc;
import view.V_SuaSinhVien;
import view.V_XoaSinhVien;
import view.V_XoaTaiKhoan;
import view.V_SuaDiem;
import view.V_SuaLop;
import view.V_SuaMonHoc;
import view.V_SuaTaiKhoan;
import view.V_TimKiemMonHoc;
import view.V_TimKiemSinhVien;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class GD_TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frm_main
     */
    public GD_TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Phần Mềm Quản Lý Điểm Sinh Viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        mn_addTK = new javax.swing.JMenuItem();
        mn_editTK = new javax.swing.JMenuItem();
        mn_deleteTK = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menu_addSV = new javax.swing.JMenuItem();
        menu_editSV = new javax.swing.JMenuItem();
        mn_deleteSV = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mn_addMH = new javax.swing.JMenuItem();
        mn_editMH = new javax.swing.JMenuItem();
        mn_deleteMH = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mn_addD = new javax.swing.JMenuItem();
        mn_editD = new javax.swing.JMenuItem();
        mn_deleteD = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mn_addL = new javax.swing.JMenuItem();
        mn_editL = new javax.swing.JMenuItem();
        mn_deleteL = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menu_TKSV = new javax.swing.JMenuItem();
        menu_TKMH = new javax.swing.JMenuItem();
        menu_thayDoiMK = new javax.swing.JMenu();
        menu_banquyen = new javax.swing.JMenu();
        cmd_thoat = new javax.swing.JMenu();

        jMenuItem16.setText("jMenuItem16");

        jMenuItem18.setText("jMenuItem18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/KMA.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));
        jMenuBar1.setToolTipText("");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Quản Lý.png"))); // NOI18N
        jMenu6.setText("Quản Trị Hệ Thống");

        jMenu9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Người Dùng.png"))); // NOI18N
        jMenu9.setText("Quản Lý Tài Khoản");

        mn_addTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thêm.png"))); // NOI18N
        mn_addTK.setText("Thêm Tài Khoản");
        mn_addTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addTKActionPerformed(evt);
            }
        });
        jMenu9.add(mn_addTK);

        mn_editTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sửa.png"))); // NOI18N
        mn_editTK.setText("Sửa Thông Tin Tài Khoản");
        mn_editTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_editTKActionPerformed(evt);
            }
        });
        jMenu9.add(mn_editTK);

        mn_deleteTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xóa.png"))); // NOI18N
        mn_deleteTK.setText("Xóa Tài Khoản");
        mn_deleteTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteTKActionPerformed(evt);
            }
        });
        jMenu9.add(mn_deleteTK);

        jMenu6.add(jMenu9);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Quản Lý.png"))); // NOI18N
        jMenu1.setText("Quản Lý");

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sinh Viên.png"))); // NOI18N
        jMenu4.setText("Sinh Viên ");

        menu_addSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thêm.png"))); // NOI18N
        menu_addSV.setText("Thêm Sinh Viên");
        menu_addSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addSVActionPerformed(evt);
            }
        });
        jMenu4.add(menu_addSV);

        menu_editSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sửa.png"))); // NOI18N
        menu_editSV.setText("Sửa Thông Tin Sinh Viên");
        menu_editSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_editSVActionPerformed(evt);
            }
        });
        jMenu4.add(menu_editSV);

        mn_deleteSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xóa.png"))); // NOI18N
        mn_deleteSV.setText("Xóa Sinh Viên");
        mn_deleteSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteSVActionPerformed(evt);
            }
        });
        jMenu4.add(mn_deleteSV);

        jMenu1.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Môn Học.png"))); // NOI18N
        jMenu5.setText("Môn Học");

        mn_addMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thêm.png"))); // NOI18N
        mn_addMH.setText("Thêm Môn Học");
        mn_addMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addMHActionPerformed(evt);
            }
        });
        jMenu5.add(mn_addMH);

        mn_editMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sửa.png"))); // NOI18N
        mn_editMH.setText("Sửa Thông Tin Môn Học");
        mn_editMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_editMHActionPerformed(evt);
            }
        });
        jMenu5.add(mn_editMH);

        mn_deleteMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xóa.png"))); // NOI18N
        mn_deleteMH.setText("Xóa Môn Học");
        mn_deleteMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteMHActionPerformed(evt);
            }
        });
        jMenu5.add(mn_deleteMH);

        jMenu1.add(jMenu5);

        jMenu7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Điểm.png"))); // NOI18N
        jMenu7.setText("Điểm");

        mn_addD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thêm.png"))); // NOI18N
        mn_addD.setText("Thêm Điểm");
        mn_addD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addDActionPerformed(evt);
            }
        });
        jMenu7.add(mn_addD);

        mn_editD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sửa.png"))); // NOI18N
        mn_editD.setText("Sửa Thông Tin Điểm");
        mn_editD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_editDActionPerformed(evt);
            }
        });
        jMenu7.add(mn_editD);

        mn_deleteD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xóa.png"))); // NOI18N
        mn_deleteD.setText("Xóa Điểm");
        mn_deleteD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteDActionPerformed(evt);
            }
        });
        jMenu7.add(mn_deleteD);

        jMenu1.add(jMenu7);

        jMenu8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lớp.png"))); // NOI18N
        jMenu8.setText("Lớp");

        mn_addL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Thêm.png"))); // NOI18N
        mn_addL.setText("Thêm Lớp");
        mn_addL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addLActionPerformed(evt);
            }
        });
        jMenu8.add(mn_addL);

        mn_editL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sửa.png"))); // NOI18N
        mn_editL.setText("Sửa Thông Tin Lớp");
        mn_editL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_editLActionPerformed(evt);
            }
        });
        jMenu8.add(mn_editL);

        mn_deleteL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Xóa.png"))); // NOI18N
        mn_deleteL.setText("Xóa Lớp");
        mn_deleteL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_deleteLActionPerformed(evt);
            }
        });
        jMenu8.add(mn_deleteL);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tìm Kiếm.png"))); // NOI18N
        jMenu10.setText("Tìm Kiếm ");

        menu_TKSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sinh Viên.png"))); // NOI18N
        menu_TKSV.setText("Tìm Kiếm Sinh Viên");
        menu_TKSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_TKSVActionPerformed(evt);
            }
        });
        jMenu10.add(menu_TKSV);

        menu_TKMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Môn Học.png"))); // NOI18N
        menu_TKMH.setText("Tìm Kiếm Môn Học");
        menu_TKMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_TKMHActionPerformed(evt);
            }
        });
        jMenu10.add(menu_TKMH);

        jMenuBar1.add(jMenu10);

        menu_thayDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Thay Đổi Mật Khẩu.png"))); // NOI18N
        menu_thayDoiMK.setText("Thay Đổi Mật Khẩu");
        menu_thayDoiMK.setToolTipText("");
        menu_thayDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_thayDoiMKMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_thayDoiMK);

        menu_banquyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bản Quyền.png"))); // NOI18N
        menu_banquyen.setText("Bản quyển");
        menu_banquyen.setToolTipText("");
        menu_banquyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_banquyenMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_banquyen);

        cmd_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout-icon.png"))); // NOI18N
        cmd_thoat.setText("Thoát");
        cmd_thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd_thoatMouseClicked(evt);
            }
        });
        jMenuBar1.add(cmd_thoat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // hiển thị form Thêm Sinh Viên
    private void menu_addSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addSVActionPerformed
        // khai báo biến
        V_ThemSinhVien addSinhVien;
        
        try {
            addSinhVien = new V_ThemSinhVien();
            addSinhVien.setVisible(true); // hiển thị form thêm sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
            Logger.getLogger(V_ThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_addSVActionPerformed
    // hiển thị form Sửa thông tin sinh viên
    private void menu_editSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_editSVActionPerformed
        // khai báo biến
        V_SuaSinhVien editSinhVien;
        try {
            editSinhVien = new V_SuaSinhVien();
            editSinhVien.setVisible(true); // hiển thị form sửa thông tin sinh viên
            this.dispose(); // ẩn form main
            
        } catch (Exception ex) {
            Logger.getLogger(V_ThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_editSVActionPerformed
    
    // hiển thị form Xóa sinh viên
    private void mn_deleteSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteSVActionPerformed
       // khai báo biến
       V_XoaSinhVien deleteSinhVien;
        try {
            deleteSinhVien = new V_XoaSinhVien();
            deleteSinhVien.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_ThemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_deleteSVActionPerformed

    private void mn_addMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addMHActionPerformed
        // TODO add your handling code here:
        V_ThemMonHoc frm_addMonHoc;
        try {
            frm_addMonHoc = new V_ThemMonHoc();
            frm_addMonHoc.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_ThemMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_addMHActionPerformed

    private void mn_addDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addDActionPerformed
        // TODO add your handling code here:
        V_ThemDiem frm_addDiem;
        try {
            frm_addDiem = new V_ThemDiem();
            frm_addDiem.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_ThemDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_addDActionPerformed

    private void mn_deleteTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteTKActionPerformed
        // TODO add your handling code here:
        V_XoaTaiKhoan deleteTaiKhoan;
        try {
            deleteTaiKhoan = new V_XoaTaiKhoan();
            deleteTaiKhoan.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_XoaTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_deleteTKActionPerformed

    private void mn_addTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addTKActionPerformed
        // TODO add your handling code here:
        V_ThemTaiKhoan frm_addTaiKhoan;
        try {
            frm_addTaiKhoan = new V_ThemTaiKhoan();
            frm_addTaiKhoan.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_ThemTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_addTKActionPerformed

    private void cmd_thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd_thoatMouseClicked
        V_DangNhap frm_login;
        frm_login = new V_DangNhap();
        frm_login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmd_thoatMouseClicked

    private void menu_banquyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_banquyenMouseClicked
        GD_BanQuyen frmsv;
        frmsv = new GD_BanQuyen();
        frmsv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_banquyenMouseClicked

    private void menu_thayDoiMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_thayDoiMKMouseClicked
        // TODO add your handling code here:
        V_ThayDoiMatKhau frmsv;
        frmsv = new V_ThayDoiMatKhau();
        frmsv.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menu_thayDoiMKMouseClicked

    private void menu_TKSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_TKSVActionPerformed
        // TODO add your handling code here:
        V_TimKiemSinhVien searchSinhVien;
        
        try {
            searchSinhVien = new V_TimKiemSinhVien();
            searchSinhVien.setVisible(true); // hiển thị form thêm sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
            Logger.getLogger(V_TimKiemSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_TKSVActionPerformed

    private void menu_TKMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_TKMHActionPerformed
        // TODO add your handling code here:
        V_TimKiemMonHoc searchMonHoc;
        
        try {
            searchMonHoc = new V_TimKiemMonHoc();
            searchMonHoc.setVisible(true); // hiển thị form thêm sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
            Logger.getLogger(V_TimKiemMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_TKMHActionPerformed

    private void mn_editLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_editLActionPerformed
        // TODO add your handling code here:
        V_SuaLop frm_editLop;
        try {
            frm_editLop = new V_SuaLop();
            frm_editLop.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_SuaLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_editLActionPerformed

    private void mn_editMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_editMHActionPerformed
        // TODO add your handling code here:
        V_SuaMonHoc frm_editMonHoc;
        try {
            frm_editMonHoc = new V_SuaMonHoc();
            frm_editMonHoc.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_SuaMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_editMHActionPerformed

    private void mn_deleteMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteMHActionPerformed
        // TODO add your handling code here:
        V_XoaMonHoc frm_deleteMonHoc;
        try {
            frm_deleteMonHoc = new V_XoaMonHoc();
            frm_deleteMonHoc.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_XoaMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_deleteMHActionPerformed

    private void mn_editDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_editDActionPerformed
        // TODO add your handling code here:
        V_SuaDiem frm_editDiem;
        try {
            frm_editDiem = new V_SuaDiem();
            frm_editDiem.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_SuaDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_editDActionPerformed

    private void mn_deleteDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteDActionPerformed
        // TODO add your handling code here:
        V_XoaDiem frm_deleteDiem;
        try {
            frm_deleteDiem = new V_XoaDiem();
            frm_deleteDiem.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_XoaDiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_deleteDActionPerformed

    private void mn_addLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addLActionPerformed
        // TODO add your handling code here:
        V_ThemLop frm_addLop;
        try {
            frm_addLop = new V_ThemLop();
            frm_addLop.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_ThemLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_addLActionPerformed

    private void mn_deleteLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_deleteLActionPerformed
        // TODO add your handling code here:
        V_XoaLop frm_deleteLop;
        try {
            frm_deleteLop = new V_XoaLop();
            frm_deleteLop.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_XoaLop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_deleteLActionPerformed

    private void mn_editTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_editTKActionPerformed
        // TODO add your handling code here:
        V_SuaTaiKhoan frm_editTaiKhoan;
        try {
            frm_editTaiKhoan = new V_SuaTaiKhoan();
            frm_editTaiKhoan.setVisible(true); // hiển thị form xóa sinh viên
            this.dispose(); // ẩn form main
        } catch (Exception ex) {
             Logger.getLogger(V_SuaTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mn_editTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cmd_thoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem menu_TKMH;
    private javax.swing.JMenuItem menu_TKSV;
    private javax.swing.JMenuItem menu_addSV;
    private javax.swing.JMenu menu_banquyen;
    private javax.swing.JMenuItem menu_editSV;
    private javax.swing.JMenu menu_thayDoiMK;
    private javax.swing.JMenuItem mn_addD;
    private javax.swing.JMenuItem mn_addL;
    private javax.swing.JMenuItem mn_addMH;
    private javax.swing.JMenuItem mn_addTK;
    private javax.swing.JMenuItem mn_deleteD;
    private javax.swing.JMenuItem mn_deleteL;
    private javax.swing.JMenuItem mn_deleteMH;
    private javax.swing.JMenuItem mn_deleteSV;
    private javax.swing.JMenuItem mn_deleteTK;
    private javax.swing.JMenuItem mn_editD;
    private javax.swing.JMenuItem mn_editL;
    private javax.swing.JMenuItem mn_editMH;
    private javax.swing.JMenuItem mn_editTK;
    // End of variables declaration//GEN-END:variables
}
